
export const actions = {
    USER_REQUEST_REGISTRATION_FAILED : "USER_REQUEST_REGISTRATION_FAILED",
    USER_REQUEST_REGISTRATION_PASSED : "USER_REQUEST_REGISTRATION_PASSED",
    USER_SIGN_IN_FAILED : "USER_SIGN_IN_FAILED",
    USER_SIGN_IN_PASSED : "USER_SIGN_IN_PASSED",
    MESSAGES_RECEIVED : "MESSAGES_RECEIVED",
    ON_TEXT_CHANGED : "ON_TEXT_CHANGED"
};
