
export const actions = {
    USER_REQUEST_REGISTRATION_FAILED : "USER_REQUEST_REGISTRATION_FAILED",
    USER_REQUEST_REGISTRATION_PASSED : "USER_REQUEST_REGISTRATION_PASSED",
    USER_SIGN_IN_FAILED : "USER_SIGN_IN_FAILED",
    USER_SIGN_IN_PASSED : "USER_SIGN_IN_PASSED",
    MESSAGES_RECEIVED : "MESSAGES_RECEIVED",
    ON_TEXT_CHANGED : "ON_TEXT_CHANGED",
    RECEIVE_USERS_FAILED : "RECEIVE_USERS_FAILED",
    RECEIVE_USERS : "RECEIVE_USERS",
    CLEAR_REGISTRATION_FIELDS : "CLEAR_REGISTRATION_FIELDS",
    CLEAR_LOGIN_FIELDS : "CLEAR_LOGIN_FIELDS",
    RESET_REGISTRATION_FLAG : "RESET_REGISTRATION_FLAG",
    RESET_LOGIN_FLAG : "RESET_LOGIN_FLAG"
};
